FROM golang:1.23-alpine AS build
WORKDIR /src
ENV GOPROXY="https://goproxy.cn|https://proxy.golang.org|direct"
COPY . .
RUN go mod tidy && CGO_ENABLED=0 go build -o /out/pctl .

FROM alpine:3.20
COPY --from=build /out/pctl /pctl
EXPOSE 8080
ENTRYPOINT ["/pctl", "serve"]
