package main

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const generatedHeader = "# ⚠️ GENERATED BY pctl sync — 手改无效，改 services/*/{service,plugin}.yaml 后重新 sync\n"

// runSync 由清单生成 gateway/kong.yml 与 docker-compose.services.yml（含 gateway/plugin-pg/网络）。
func runSync(root string) error {
	manifests, err := loadManifests(root)
	if err != nil {
		return err
	}
	if err := validateManifests(manifests); err != nil {
		return err
	}
	pubPEM, err := ensureKeys(root)
	if err != nil {
		return err
	}

	var enabled []Manifest
	for _, m := range manifests {
		if m.IsEnabled() {
			enabled = append(enabled, m)
		} else {
			fmt.Printf("  %s: disabled，跳过\n", m.ID)
		}
	}

	if v := envFromRoot(root, "PF_REDIS_URL"); v != "" {
		os.Setenv("PF_REDIS_URL", v)
	} else {
		os.Setenv("PF_REDIS_URL", "redis://redis:6379/0")
	}
	kong := renderKong(enabled, pubPEM, redisRateLimit())
	if err := os.WriteFile(filepath.Join(root, "gateway", "kong.yml"), []byte(kong), 0o644); err != nil {
		return fmt.Errorf("write kong.yml: %w", err)
	}
	compose := renderServicesCompose(enabled)
	if err := os.WriteFile(filepath.Join(root, "docker-compose.services.yml"), []byte(compose), 0o644); err != nil {
		return fmt.Errorf("write docker-compose.services.yml: %w", err)
	}
	fmt.Printf("sync 完成：%d 个服务（enabled）→ kong.yml + docker-compose.services.yml\n", len(enabled))
	return nil
}

// ensureKeys 保证 RS256 密钥对存在（与 auth 的生成逻辑幂等互备），返回公钥 PEM。
func ensureKeys(root string) (string, error) {
	privPath := filepath.Join(root, ".keys", "pf-auth.pem")
	pubPath := privPath + ".pub"
	if raw, err := os.ReadFile(pubPath); err == nil {
		return string(raw), nil
	}
	key, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(filepath.Dir(privPath), 0o755); err != nil {
		return "", err
	}
	privPEM := pem.EncodeToMemory(&pem.Block{Type: "RSA PRIVATE KEY", Bytes: x509.MarshalPKCS1PrivateKey(key)})
	if err := os.WriteFile(privPath, privPEM, 0o600); err != nil {
		return "", err
	}
	pubDER, err := x509.MarshalPKIXPublicKey(&key.PublicKey)
	if err != nil {
		return "", err
	}
	pubPEM := pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: pubDER})
	if err := os.WriteFile(pubPath, pubPEM, 0o644); err != nil {
		return "", err
	}
	fmt.Println("已生成 RS256 密钥对 → .keys/（gitignore；生产环境用密钥管理分发）")
	return string(pubPEM), nil
}

func readEnvVar(path, key string) (string, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	for _, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		k, v, ok := strings.Cut(line, "=")
		if ok && strings.TrimSpace(k) == key {
			return strings.Trim(strings.TrimSpace(v), `"'`), nil
		}
	}
	return "", fmt.Errorf("%s not in %s", key, path)
}

func envFromRoot(root, key string) string {
	if v := strings.TrimSpace(os.Getenv(key)); v != "" {
		return v
	}
	v, err := readEnvVar(filepath.Join(root, ".env"), key)
	if err != nil {
		return ""
	}
	return strings.TrimSpace(v)
}

func redisRateLimit() bool {
	v := strings.TrimSpace(os.Getenv("PF_REDIS_URL"))
	return v != "" && v != "0" && strings.ToLower(v) != "false"
}

func rateLimitYAML(minute int, indent string) string {
	if redisRateLimit() {
		return fmt.Sprintf("%s- name: rate-limiting\n%s  config: { minute: %d, policy: redis, redis: { host: redis, port: 6379, timeout: 2000 }, limit_by: ip }\n", indent, indent, minute)
	}
	return fmt.Sprintf("%s- name: rate-limiting\n%s  config: { minute: %d, policy: local, limit_by: ip }\n", indent, indent, minute)
}

func renderKong(manifests []Manifest, pubPEM string, _ bool) string {
	var b strings.Builder
	b.WriteString("_format_version: \"3.0\"\n\n")
	b.WriteString(generatedHeader)
	b.WriteString("services:\n")
	b.WriteString("  - name: auth\n    url: http://auth:8080\n    retries: 2\n    routes:\n")
	b.WriteString("      - name: auth-route\n        paths: [\"/auth\"]\n        strip_path: false\n        plugins:\n")
	b.WriteString(rateLimitYAML(60, "          "))
	b.WriteString("      - name: platform-root\n        paths: [\"/\"]\n        strip_path: false\n")
	for _, m := range manifests {
		fmt.Fprintf(&b, "\n  - name: %s\n    url: http://%s:%d\n    retries: 2\n    routes:\n", m.ID, m.ID, m.Runtime.Port)
		for i, p := range publicPrefixes(m) {
			fmt.Fprintf(&b, "      - name: %s-public-%d\n        paths: [\"%s\"]\n        strip_path: %v\n", m.ID, i, p, m.Mount.StripPath)
		}
		fmt.Fprintf(&b, "      - name: %s-protected\n        paths: [\"%s\"]\n        strip_path: %v\n", m.ID, m.Mount.Path, m.Mount.StripPath)
		if m.Auth.Required || m.Limits.RatePerMinute > 0 {
			b.WriteString("        plugins:\n")
		}
		if m.Auth.Required {
			b.WriteString("          - name: jwt\n            config: { key_claim_name: iss, claims_to_verify: [\"exp\"] }\n")
		}
		if m.Limits.RatePerMinute > 0 {
			b.WriteString(rateLimitYAML(m.Limits.RatePerMinute, "          "))
		}
	}
	b.WriteString(`
# jwt 插件按 iss=pf-auth 匹配此 consumer，RS256 公钥验签（私钥仅 auth 持有）
consumers:
  - username: pf-auth-issuer
    jwt_secrets:
      - key: pf-auth
        algorithm: RS256
        rsa_public_key: |
`)
	for _, line := range strings.Split(strings.TrimRight(pubPEM, "\n"), "\n") {
		b.WriteString("          " + line + "\n")
	}
	return b.String()
}
