package main

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const generatedHeader = "# ⚠️ GENERATED BY pctl sync — 手改无效，改 services/*/{service,plugin}.yaml 后重新 sync\n"

// runSync 由清单生成 gateway/kong.yml 与 docker-compose.services.yml（含 gateway/plugin-pg/网络）。
func runSync(root string) error {
	manifests, err := loadManifests(root)
	if err != nil {
		return err
	}
	if err := validateManifests(manifests); err != nil {
		return err
	}
	pubPEM, err := ensureKeys(root)
	if err != nil {
		return err
	}

	var enabled []Manifest
	for _, m := range manifests {
		if m.IsEnabled() {
			enabled = append(enabled, m)
		} else {
			fmt.Printf("  %s: disabled，跳过\n", m.ID)
		}
	}

	kong := renderKong(enabled, pubPEM)
	if err := os.WriteFile(filepath.Join(root, "gateway", "kong.yml"), []byte(kong), 0o644); err != nil {
		return fmt.Errorf("write kong.yml: %w", err)
	}
	compose := renderServicesCompose(enabled)
	if err := os.WriteFile(filepath.Join(root, "docker-compose.services.yml"), []byte(compose), 0o644); err != nil {
		return fmt.Errorf("write docker-compose.services.yml: %w", err)
	}
	fmt.Printf("sync 完成：%d 个服务（enabled）→ kong.yml + docker-compose.services.yml\n", len(enabled))
	return nil
}

// ensureKeys 保证 RS256 密钥对存在（与 auth 的生成逻辑幂等互备），返回公钥 PEM。
func ensureKeys(root string) (string, error) {
	privPath := filepath.Join(root, ".keys", "pf-auth.pem")
	pubPath := privPath + ".pub"
	if raw, err := os.ReadFile(pubPath); err == nil {
		return string(raw), nil
	}
	key, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(filepath.Dir(privPath), 0o755); err != nil {
		return "", err
	}
	privPEM := pem.EncodeToMemory(&pem.Block{Type: "RSA PRIVATE KEY", Bytes: x509.MarshalPKCS1PrivateKey(key)})
	if err := os.WriteFile(privPath, privPEM, 0o600); err != nil {
		return "", err
	}
	pubDER, err := x509.MarshalPKIXPublicKey(&key.PublicKey)
	if err != nil {
		return "", err
	}
	pubPEM := pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: pubDER})
	if err := os.WriteFile(pubPath, pubPEM, 0o644); err != nil {
		return "", err
	}
	fmt.Println("已生成 RS256 密钥对 → .keys/（gitignore；生产环境用密钥管理分发）")
	return string(pubPEM), nil
}

func renderKong(manifests []Manifest, pubPEM string) string {
	var b strings.Builder
	b.WriteString("_format_version: \"3.0\"\n\n")
	b.WriteString(generatedHeader)
	b.WriteString(`
services:
  # ── auth 底座（平台静态部分）：/auth 公开，/internal 不路由 ──
  - name: auth
    url: http://auth:8080
    routes:
      - name: auth-route
        paths: ["/auth"]
        strip_path: false
        plugins:
          - name: rate-limiting
            config: { minute: 60, policy: local, limit_by: ip }
      - name: platform-root # 根路径平台信息 + 未匹配路径的 JSON 404 兜底（auth 处理）
        paths: ["/"]
        strip_path: false
`)
	for _, m := range manifests {
		fmt.Fprintf(&b, "\n  - name: %s\n    url: http://%s:%d\n    routes:\n", m.ID, m.ID, m.Runtime.Port)
		for i, p := range publicPrefixes(m) {
			fmt.Fprintf(&b, "      - name: %s-public-%d\n        paths: [\"%s\"]\n        strip_path: %v\n", m.ID, i, p, m.Mount.StripPath)
		}
		fmt.Fprintf(&b, "      - name: %s-protected\n        paths: [\"%s\"]\n        strip_path: %v\n", m.ID, m.Mount.Path, m.Mount.StripPath)
		if m.Auth.Required || m.Limits.RatePerMinute > 0 {
			b.WriteString("        plugins:\n")
		}
		if m.Auth.Required {
			b.WriteString("          - name: jwt\n            config: { key_claim_name: iss, claims_to_verify: [\"exp\"] }\n")
		}
		if m.Limits.RatePerMinute > 0 {
			fmt.Fprintf(&b, "          - name: rate-limiting\n            config: { minute: %d, policy: local, limit_by: ip }\n", m.Limits.RatePerMinute)
		}
	}
	b.WriteString(`
# jwt 插件按 iss=pf-auth 匹配此 consumer，RS256 公钥验签（私钥仅 auth 持有）
consumers:
  - username: pf-auth-issuer
    jwt_secrets:
      - key: pf-auth
        algorithm: RS256
        rsa_public_key: |
`)
	for _, line := range strings.Split(strings.TrimRight(pubPEM, "\n"), "\n") {
		b.WriteString("          " + line + "\n")
	}
	return b.String()
}
